# This has been created by @lillieH1000

name: Build the YouTube Music Premium Deb

on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build YouTube Music Premium
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout chrisharper22/sdks
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Build Package 
        run: |
          brew install make xz ldid 
          export THEOS=theos
          gmake clean package SIDELOADING=1
          gmake clean package ROOTLESS=1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/*.deb
